from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
import httpx
import os
from dotenv import load_dotenv

load_dotenv()

app = FastAPI()

# ponytail: ordered fallback list is the retry strategy; one attempt per provider
# NVIDIA last: its free tier queues requests (~60s+ latency), so it's the last resort
PROVIDERS = [
    ("Groq", "https://api.groq.com/openai/v1/chat/completions",
     "GROQ_API_KEY", "llama-3.3-70b-versatile"),
    ("Gemini", "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
     "GEMINI_API_KEY", "gemini-2.5-flash"),
    ("NVIDIA", "https://integrate.api.nvidia.com/v1/chat/completions",
     "NVIDIA_API_KEY", "meta/llama-3.1-8b-instruct"),
]


class RecipeRequest(BaseModel):
    ingredients: str


@app.post("/generate-recipe")
async def generate_recipe(request: RecipeRequest):
    prompt = f"""You are a professional chef AI assistant. Create a detailed recipe using the following ingredients: {request.ingredients}.

Please provide:
1. Recipe name
2. Cooking time
3. Difficulty level
4. Complete ingredients list (including quantities)
5. Step-by-step cooking instructions
6. Nutritional highlights
7. Serving suggestions

Format the response in a clear, easy-to-read structure. If some common kitchen staples are needed (salt, pepper, oil), feel free to include them."""

    errors = []
    async with httpx.AsyncClient(timeout=150.0) as client:
        for name, url, key_var, model in PROVIDERS:
            key = os.getenv(key_var)
            if not key:
                errors.append(f"{name}: no API key set")
                continue
            try:
                response = await client.post(
                    url,
                    headers={"Authorization": f"Bearer {key}"},
                    json={
                        "model": model,
                        "messages": [{"role": "user", "content": prompt}],
                        "temperature": 0.7,
                        "max_tokens": 4096,
                    },
                )
                if response.status_code == 200:
                    recipe = response.json()["choices"][0]["message"]["content"]
                    print(f"Recipe generated by {name}, length: {len(recipe)}")
                    return {"recipe": recipe, "provider": name}
                errors.append(f"{name}: HTTP {response.status_code}")
                print(f"{name} failed ({response.status_code}): {response.text[:200]}")
            except (httpx.HTTPError, KeyError, IndexError) as e:
                errors.append(f"{name}: {type(e).__name__}")
                print(f"{name} failed: {e!r}")

    raise HTTPException(
        status_code=503,
        detail="All AI providers unavailable: " + "; ".join(errors),
    )


@app.get("/health")
async def health_check():
    return {"status": "ok"}


# Must come after the API routes — catch-all static mount
app.mount("/", StaticFiles(directory="frontend-main", html=True), name="frontend")


if __name__ == "__main__":
    import uvicorn

    host = os.getenv("HOST", "127.0.0.1")
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run("main:app", host=host, port=port, reload=True)
